### ISSUE TITLE
Audio Files Cannot be Played in iOS Browser

### ISSUE THREAD

**Issue by akeybl** [tinode/webapp#122]
STR:
1) Use Google Chrome on a Mac to go to https://sandbox.tinode.co/
2) Log in with alice/alice123
3) Click on Carol Xmas
4) Click microphone icon in bottom right-hand corner, allow microphone permission
5) Say something, hit send, confirm playback
7) Switch to Chrome on iOS and go to https://sandbox.tinode.co/
8) Click on Carol Xmas

![IMG_A1321BA6DBD7-1](https://user-images.githubusercontent.com/1084865/231553261-89ced614-a88e-4dd7-9855-a934979b003d.jpeg)

Note that I'm using Chrome on iOS to prevent content blockers and extensions from interfering with the STR.

**Comment by or-else** [comment]
The problem here is that Chrome records audio in `webm` format but neither Chrome nor Safari is able to play `webm` on iOS. I suspect it's intentionally crippled by Apple. 
I don't see any options for supporting playback in a browser on iOS other than transcoding audio on the server. That's a lot of work. I don't think we are going to do it any time soon. 
Please use a native app.

**Comment by or-else** [comment]
I fixed some issues with playback. It no longer crashes, the preview bars do not have gaps anymore. Once this fix https://github.com/tinode/chat/commit/dda74cddc9d4f8750b38f86e65925e74eb4a8e3e is deployed, audio recorded in Safari will play in Safari.

**Comment by or-else** [comment]
No updates, so I assume all is fine. Closing as fixed.

**Comment by akeybl** [comment]
Apologies for the delay, confirmed working!
