### ISSUE TITLE
Every Refresh Download

### ISSUE THREAD

**Issue by yash0924** [tinode/webapp#14]
When I reload the application in chrome, it downloads the file which is of zero kb

**Comment by or-else** [comment]
I've seen that happen sometimes right after deploying a new version but I'm not sure why. See if this helps: https://gundersen.net/chrome-downloading-file-instead-of-displaying-page-solved/

**Comment by or-else** [comment]
I think figured out what's happening. When browser cache is enabled and the app is downloaded once, the client sends a `If-modified-since` header with subsequent requests. The server responses with `304 Not Modified` which is compressed and served with an incorrect header `Content-Type: application/x-gzip` and as such saved to browser cache. Then the incorrect file is served from there.

**Comment by yash0924** [comment]
after deleting the browser past data, still issue persist.

**Comment by or-else** [comment]
I found and fixed the bug: https://github.com/tinode/chat/commit/9b0ca941a9a39d93eba64a262faf5bd317685ce5

Thanks for the bug report!

Will push a new release in a couple of hours.

**Comment by or-else** [comment]
Released 0.15.5-rc3 with the fix, verified that it's indeed fixed.
