### ISSUE TITLE
[Question] Web app with separated html, css and js files instead of single-page app?

### ISSUE THREAD

**Issue by pwFoo** [tinode/webapp#23]
I like tinode and the web app client, but I think it would be easier to extend and maintain if the code would be separated in html / template, css and js files instead of a single-page app?

If other people interested in such a web app and maybe could help with testing and comits I could take a look into tinode.js, do some tests and start it. I don't know if I have the time and experience to finish it, but I would give it a try.

**Comment by or-else** [comment]
CSS is already separated into a file. As for separating js from html, Generally React expects components to have js and html in one file: https://reactjs.org/docs/introducing-jsx.html 

On the other hand I agree that a single file is inconvenient. I've split it into components in `i18n` branch: https://github.com/tinode/webapp/tree/i18n/src

I would certainly support efforts to simplify or otherwise improve the app.

**Comment by pwFoo** [comment]
If I start to build it, I wouldn't use react because I don't know it...
I would try to build it as simple as possible with some small js libs and html.

If each html snippet is only in one place it should be easier to understand and work with.

**Comment by or-else** [comment]
React is not bad. It's quite convenient for building large js apps and it's well supported. I also did not know it before I started with this project.
