### ISSUE TITLE
Using already registered Email address for new registration won't get error warning until validation code is entered 

### ISSUE THREAD

**Issue by hanqo** [tinode/webapp#27]
I tried to register (sign up) a new account with an already registered Email, and it succeeds at the first step and I received the verification code via email. But when I entered the code and click confirm, a warning came out saying that duplicated credentials. I would expect that this warning should come in the first step and the verification Email should not be sent if it's already registered. Is that the design like so or it's a bug?

**Comment by or-else** [comment]
It's by design. It's not a bug.
 
The logic here is to prevent scraping of emails: if a malicious agent wants to know if someone is using email john@example.com he tries to register the new account using john@example.com. If the warning is given immediately, the agent knows that there is a user with the email john@example.com. With the current scheme the agent cannot get this information at all.
