### ISSUE TITLE
multiple listener support

### ISSUE THREAD

**Issue by pcgpcgpcg** [tinode/webapp#39]
now in web app, tinode.js only allow one callback for a promise.
but some situation we want multiple callback as listener ,because many react component may pay attention to the promise not only tinodeweb.jsx  .
so is it better to use callback list   or   redux-thunk /saga?

**Comment by or-else** [comment]
There is no material difference between callbacks and promises. They serve the same use cases in largely the same way. The differences are purely syntactic. 

You probably have experience with callbacks and less experience with promises that's why you think callbacks can do what promises can't. That's not the case. Promises can do whatever callbacks can do, no difference.

**Comment by pcgpcgpcg** [comment]
no, i didn't mean promise,  I mean the difference between callback  and callbackList,  Another word is the difference between single listener and many listener.      Assume such circumstance ,   if   both class tinodeweb and class loginview want to listen  OnConnected, current tinode.js can't publish the onConnected event to these two components! That's the problem

**Comment by pcgpcgpcg** [comment]
I think write a  middleware between tinode.js and React UI components is necessary.  I'll try to write the middleware and share the point view.

**Comment by or-else** [comment]
You are welcome to send a pull request.

**Comment by pcgpcgpcg** [comment]
thank you ! I'll pay my best effort to verify this

**Comment by or-else** [comment]
This has been open for over a year with no updates. Closing?
